# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdfs.exists <- function(path) {
    .Call('rmr2_hdfs_exists', PACKAGE = 'rmr2', path)
}

hdfs.cp <- function(src, dst) {
    .Call('rmr2_hdfs_copy', PACKAGE = 'rmr2', src, dst)
}

hdfs.get <- function(src, dst) {
    .Call('rmr2_hdfs_get', PACKAGE = 'rmr2', src, dst)
}

hdfs.put <- function(src, dst) {
    .Call('rmr2_hdfs_put', PACKAGE = 'rmr2', src, dst)
}

hdfs.mv <- function(src, dst) {
    .Call('rmr2_hdfs_mv', PACKAGE = 'rmr2', src, dst)
}

hdfs.rm <- function(path, recursive = FALSE) {
    .Call('rmr2_hdfs_rm', PACKAGE = 'rmr2', path, recursive)
}

hdfs.mkdir <- function(path) {
    .Call('rmr2_hdfs_mkdir', PACKAGE = 'rmr2', path)
}

hdfs_ls <- function(path) {
    .Call('rmr2_hdfs_ls', PACKAGE = 'rmr2', path)
}

hdfs_file_info <- function(path) {
    .Call('rmr2_hdfs_file_info', PACKAGE = 'rmr2', path)
}

