// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hdfs_exists
bool hdfs_exists(const char * path);
RcppExport SEXP rmr2_hdfs_exists(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type path(pathSEXP );
        bool __result = hdfs_exists(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_copy
bool hdfs_copy(const char * src, const char * dst);
RcppExport SEXP rmr2_hdfs_copy(SEXP srcSEXP, SEXP dstSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type src(srcSEXP );
        Rcpp::traits::input_parameter< const char * >::type dst(dstSEXP );
        bool __result = hdfs_copy(src, dst);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_get
bool hdfs_get(const char * src, const char * dst);
RcppExport SEXP rmr2_hdfs_get(SEXP srcSEXP, SEXP dstSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type src(srcSEXP );
        Rcpp::traits::input_parameter< const char * >::type dst(dstSEXP );
        bool __result = hdfs_get(src, dst);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_put
bool hdfs_put(const char * src, const char * dst);
RcppExport SEXP rmr2_hdfs_put(SEXP srcSEXP, SEXP dstSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type src(srcSEXP );
        Rcpp::traits::input_parameter< const char * >::type dst(dstSEXP );
        bool __result = hdfs_put(src, dst);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_mv
bool hdfs_mv(const char* src, const char* dst);
RcppExport SEXP rmr2_hdfs_mv(SEXP srcSEXP, SEXP dstSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char* >::type src(srcSEXP );
        Rcpp::traits::input_parameter< const char* >::type dst(dstSEXP );
        bool __result = hdfs_mv(src, dst);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_rm
bool hdfs_rm(const char * path, bool recursive = false);
RcppExport SEXP rmr2_hdfs_rm(SEXP pathSEXP, SEXP recursiveSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type path(pathSEXP );
        Rcpp::traits::input_parameter< bool >::type recursive(recursiveSEXP );
        bool __result = hdfs_rm(path, recursive);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_mkdir
bool hdfs_mkdir(const char * path);
RcppExport SEXP rmr2_hdfs_mkdir(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type path(pathSEXP );
        bool __result = hdfs_mkdir(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_ls
List hdfs_ls(const char * path);
RcppExport SEXP rmr2_hdfs_ls(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type path(pathSEXP );
        List __result = hdfs_ls(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// hdfs_file_info
List hdfs_file_info(const char * path);
RcppExport SEXP rmr2_hdfs_file_info(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type path(pathSEXP );
        List __result = hdfs_file_info(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
