# Compatibility testing for rmr 3.1.2
In the table at the bottom we collect results concerning compatibility of rmr with a given combination of R/OS and Hadoop releases. We collect both positive and negative results if available. If a combination is not present in this table, it doesn't imply lack of compatibility. In case of negative results, we may consider them bugs in need to be addressed or not, depending how common and recent the platform combination is. Compatibility is defined as passing `R CMD  check path-to-rmr` successfully and requires an additional dependency, quickcheck, also downloadable from our wiki. Failures on producing documentation in legacy formats are not important. Notes and warnings are not important in the sense that they do not determine compatibility, but it may be helpful to report them in the issue tracker.Please contribute with additional reports. 
If you are interested in the compatibility chart for other releases, choose one from the drop down menu on the top left, under tags and find this document again (under docs). Not every release gets a complete round of testing, so typically a bug fix release (change in the third number only) is equally or more compatible than the previous release, even if we don't have the resources to test it directly. 

<table>
<thead>
<tr><th>Hadoop</th><th>R</th><th>OS</th><th>Notes</th><th>Reporter</th></tr>
</thead>
<tbody>
<tr><td>CDH4.7.0</td><td>R 3.0.2 (Revolution R 7.0)</td><td>CentOS 6.3</td><td>mr1</td><td><a href=mailto:rhadoop@revolutionanalytics.com>Revolution</a></td></tr>
</tbody>
</table>
